sonar.projectKey=Youhorng_assignment7-complete-cicd-pipeline-with-terraform
sonar.organization=youhorng

sonar.sources=.
sonar.exclusions=fonts/**,images/**,**/*.min.js,**/*.min.css,terraform/**

sonar.sourceEncoding=UTF-8
